name: DevSecOps - Snyk SAST

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    
jobs:
  snyk-sast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (if your project uses Node, change if needed)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (adjust if your language differs)
        run: npm install

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk SAST (Code Analysis)
        run: snyk code test
